Add Tides Controller and Test
ucsb-cs156-w24/team01-w24-5pm-2 pull request #23
Opened 2024-01-26 02:22 UTC by Maria-Saucedo

In this PR, we add  an endpoint '/api/tides/get' that can be used to get the information of high tides and low tides over an interval of dates.

Tides-Controller Dev Deployment: http://team01-maria-saucedo-dev.dokku-06.cs.ucsb.edu/swagger-ui/index.html 

Closes #13

2024-01-27 22:07 UTC, jiaqiguan2003 commented
LGTM!

2024-01-29 02:05 UTC, jonathan-herring commented
LGTM

2024-01-29 21:55 UTC, jiaqiguan2003 approved these changes
LGTM

2024-01-30 19:31 UTC, livitsimple commented
LGTM!

2024-01-31 01:17 UTC, aqiu28517 requested changes
Deployment looks good during testing.

There's a stray "fix this" comment in TidesQueryServiceTests.java, but once you delete that, LGTM!

2024-01-31 01:23 UTC, Maria-Saucedo commented
> Deployment looks good during testing.
> 
> There's a stray "fix this" comment in TidesQueryServiceTests.java, but once you delete that, LGTM!

Commented out code has been removed, thank you!

2024-01-31 01:32 UTC, aqiu28517 approved these changes
LGTM!

2024-01-31 02:01 UTC, merged