Add PublicHoliday Controller and Tests
ucsb-cs156-w24/team01-w24-5pm-2 pull request #27
Opened 2024-01-30 02:49 UTC by livitsimple

In this PR, we add an endpoint `/api/publicholidays/get` that can be used to get information
about the year and country code of a particular public holiday.

dev deployment link: http://team01-livitsimple-dev.dokku-06.cs.ucsb.edu

Closes #11

2024-01-30 04:31 UTC, Maria-Saucedo requested changes
You're missing the descriptions in PublicHolidayController, they should be added here (lines 35, 36) name=" ", description=" ", example=" "

The positions of paramaters year and countryCode should be swapped so they appear in the correct order on the Swagger UI page

Also, your example for country doesn't match the example given by the staff. It should be "US, MX, CN", not just US

Check out the sample UI we're given here for the correct text to input:
http://team01.dokku-00.cs.ucsb.edu/swagger-ui/index.html

2024-01-31 01:31 UTC, Maria-Saucedo approved these changes
Thanks for the quick fix, LGTM!

2024-01-31 01:42 UTC, aqiu28517 approved these changes
I think your order is fine; even though it's different from the example site. In fact, the example site doesn't even work with the API, while your order does. LGTM!

2024-01-31 03:40 UTC, jiaqiguan2003 approved these changes
LGTM

2024-02-01 00:43 UTC, merged